# - Type: Training
#   Trainers: 
#     - Name: Abraham Aranguren
#       Email: admin@7asecurity.com
#       Image: /assets/images/trainers/
#       Twitter: trainer_uno
#       Biography: >-
#           Basic Biography
#       TrainerId: trainer001
#   Title: Hacking Modern Web Apps - Master the Future of Attack Vectors
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Description
# - Type: Training
#   Trainers: 
#     - Name: Gian-Luca Frei
#       Email: gian-luca.frei@zuehlke.com
#       Image: /assets/images/trainers/
#       Twitter: trainer_uno
#       Biography: >-
#           Gian-Luca Frei is an experienced Application Security Consultant based in Singapore, currently working at Zühlke. With a passion for security, Gian-Luca has a proven track record of securing systems with the highest security standards, including e-banking portals and health applications. He brings a wealth of knowledge and expertise in the field of application security, having worked in the industry for several years. Gian-Luca is also the founder and co-leader of the OWASP Application Gateway Project, which focuses on developing open-source tools to help secure web applications. In addition to his professional engagements, Gian-Luca is a researcher at heart. He has a keen interest in modern cryptographic protocols and has conducted extensive research in this field. His contributions have been recognized with the ISSS Excellence Award in 2019.
#       TrainerId: trainer002
#   Title: Don’t trust my input: Frontend Security for Developers and Testers
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Description
# - Type: Training
#   Trainers: 
#     - Name: Abdessamad Temmar
#       Email: temmar.abdessamad@gmail.com
#       Image: /assets/images/trainers/
#       Twitter: trainer_uno
#       Biography: >-
#           Abdessamad Temmar is an appsec engineer at an asset management french company, and an active contributor to the OWASP community. Previous speaking engagements includes both DevOps and Security/Hacking conferences. 
#       TrainerId: trainer003
#   Title: API Security Testing 101
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Description
