# - Type: Training
#   Trainers: 
#     - Name: Ashwin Shenoi
#       Email: ashwin@7asecurity.com
#       Image: /assets/images/trainers/
#       Twitter: @c3rb3ru5
#       Biography: >-
#           Ashwin Shenoi is an avid application security enthusiast who currently works as a Senior Security Engineer at CRED and likes to break into applications and automate stuff. He is part of team bi0s, the top ranked CTF team according to CTFTime. He heads the Web Security team at team bi0s and is also the core challenge setter and organiser of the various editions of InCTF and the other CTFs organised by team bi0s. He is also a Security Trainer with 7ASecurity and has presented talks and security trainings in various security conferences including BlackHat Asia, BlackHat USA, BlackHat Europe, Nullcon, ThreatCon etc. He does a fair share of breaking into open source applications services and has also been awarded several CVEs for the same.
#       TrainerId: trainer001
#   Title: Hacking Modern Web Apps - Master the Future of Attack Vectors
#   SectionId: sku_IWAHBB
#   Description: >-
       This course is a 100% hands-on deep dive into the OWASP Mobile Security Testing Guide (MSTG) and relevant items of the OWASP Mobile Application Security Verification Standard (MASVS). This course covers - and goes beyond - the OWASP Mobile Top Ten. Long are the days since web servers were run by perl scripts apps written in Delphi. What is common between Walmart, eBay, PayPal, Microsoft, LinkedIn, Google and Netflix? They all use Node.js JavaScript on the server. Modern Web apps share traditional attack vectors and also introduce new opportunities to threat actors. This course will teach you how to review modern web apps, showcasing Node.js but using techniques that will also work against any other web app platform. Ideal for Penetration Testers, Web app Developers as well as everybody interested in JavaScript/Node.js and Modern app stack security. All action, no fluff, improve your security analysis workflow and immediately apply these gained skills in your workplace, packed with exercises, extra-mile challenges and CTF, self-paced and suitable for all skill levels, with continued education via unlimited email support, lifetime access, step-by-step video recordings and interesting apps to practice, including all future updates for free.
# - Type: Training
#   Trainers: 
#     - Name: Gian-Luca Frei
#       Email: gian-luca.frei@zuehlke.com
#       Image: /assets/images/trainers/
#       Twitter: trainer_uno
#       Biography: >-
#           Gian-Luca Frei is an experienced Application Security Consultant based in Singapore, currently working at Zühlke. With a passion for security, Gian-Luca has a proven track record of securing systems with the highest security standards, including e-banking portals and health applications. He brings a wealth of knowledge and expertise in the field of application security, having worked in the industry for several years. Gian-Luca is also the founder and co-leader of the OWASP Application Gateway Project, which focuses on developing open-source tools to help secure web applications. In addition to his professional engagements, Gian-Luca is a researcher at heart. He has a keen interest in modern cryptographic protocols and has conducted extensive research in this field. His contributions have been recognized with the ISSS Excellence Award in 2019.
#       TrainerId: trainer002
#   Title: Don’t trust my input: Frontend Security for Developers and Testers
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Description
# - Type: Training
#   Trainers: 
#     - Name: Abdessamad Temmar
#       Email: temmar.abdessamad@gmail.com
#       Image: /assets/images/trainers/
#       Twitter: trainer_uno
#       Biography: >-
#           Abdessamad Temmar is an appsec engineer at an asset management french company, and an active contributor to the OWASP community. Previous speaking engagements includes both DevOps and Security/Hacking conferences. 
#       TrainerId: trainer003
#   Title: API Security Testing 101
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Description
